---
title: "Introdução ao geoprocessamento com QGIS"
subtitle: "Semana de Estudos da Biologia - Unesp Rio Claro"
author: "Maurício Vancine"
date: "08/10/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Resumo

O municurso oferecerá alguns dos principais conceitos teórico-práticos de geoprocessamento no QGIS. Serão abordados os seguintes tópicos: (1) apresentações, (2) conceitos gerais de geoprocessamento, (3) instalação, interface e projeto do QGIS, (4) importação, criação, edição e operações de dados vetoriais, (5) importação, criação, edição e operações de dados matriciais, (6) composição de mapas. Após a realização do minicurso, espera-se que as alunas e alunos adquiram conceitos gerais da estrutura, manipulação e visualização de dados geoespaciais, assim como habilidades básicas para produzir mapas simples utilizando o QGIS.

## Carga horária

03 h

## Repositório do GitHub

[https://github.com/mauriciovancine/workshop-qgis](https://github.com/mauriciovancine/workshop-qgis)

## Pré-requisitos

Conhecimentos básicos de cartografia, sensoriamento retomo e sistema de informação geográfico são bem-vindos, mas não são exigidos.

## Ministrante

Maurício Vancine é Bacharel em Ecologia, Mestre em Zoologia e Doutorando em Ecologia, Evolução e Biodiversidade pela UNESP de Rio Claro. Possui experiência em Ecologia Espacial, Ecologia da Paisagem, Modelos de Distribuição de Espécies e Ecologia de Anfíbios.

Mais informações:

- Website: [https://mauriciovancine.github.io/](https://mauriciovancine.github.io/) 
- Twitter: [https://twitter.com/mauriciovancine](https://twitter.com/mauriciovancine)
- GitHub: [https://github.com/mauriciovancine](https://github.com/mauriciovancine)

## Conteúdo

### 1 Apresentação (10 min)

1. Apresentações
1. Minicurso
1. Slides
1. Material
1. Conferindo os computadores

### 2 Conceitos gerais de geoprocessamento (30 min.)

1. Geoprocessamento
1. Cartografia
1. *Global Positioning System* (GPS)
1. Sensoriamento Remoto
1. Sistema de Informação Geográfica (SIG)
1. Dados geoespaciais
1. Dados vetoriais
1. Dados matriciais (gride ou raster)
1. Conversão de dados geoespaciais (vetor-raster)
1. Banco de dados geoespaciais
1. Principais fontes de dados geoespaciais
1. Material para estudo sobre geoprocessamento

### 3 Instalação, interface e projeto do QGIS  (20 min.)

1. Histórico e vantagens do QGIS
1. Instalação do QGIS 
1. Interface do QGIS
1. Complementos do QGIS
1. Ferramentas do QGIS
1. Projeto do QGIS

### 4 Importação, criação, edição e operações de dados vetoriais  (40 min.)

1. Importar dados vetoriais
1. Propriedades de dados vetoriais
1. Tabela de atributos
1. Criar dados vetoriais
1. Editar dados vetoriais
1. Operações de dados vetoriais
1. Converter SRC de dados vetoriais
1. Exportar dados vetoriais

### 5 Importação, criação, edição e operações de dados matriciais (40 min.)

1. Importar dados matriciais
1. Propriedades de dados matriciais
1. Operações de dados vetoriais
1. Converter SRC de dados matriciais
1. Exportar dados matriciais

### 6 Composição de mapas (40 min.)

1. Principais elementos de um mapa
  1. Mapa principal
  1. Mapa secundário
  1. Título
  1. Legenda
  1. Barra de escala
  1. Indicador de orientação (Norte)
  1. Grade de coordenadas
  1. Descrição do SRC
  1. Fonte dos dados
1. Compositor de mapas
1. Exportar mapa

## Bibliografia

Bossle RC. 2017. QGIS e geoprocessamento na prática. 2 ed. Íthala. [[link]](https://ecojustus.com.br/livro/11597/livro+qgis+e+geoprocessamento+na+pratica++2%C2%AA+edicaor85)

Bossle RC. 2016. QGIS do ABC ao XYZ. Íthala. [[link]](https://ecojustus.com.br/livro/11599/livro+qgis+do+abc+ao+xyzr8)

Dalla Corte AP, Silva CA, Sanquetta CR, Rex FE, Pfutz IFP, Macedo RC. 2020. Explorando o QGIS 3.X. [[link]](https://raw.githubusercontent.com/anadallacorte/LIVROQGIS2020/main/LIVRO_QGIS_2020_21_10_2020_PUBLICADO_BAIXA.pdf)

Fitz PR. 2008. Geoprocessamento sem complicação. Oficina de Textos. [[link]](https://www.ofitexto.com.br/livro/geoprocessamento-sem-complicacao/)

Lang S, Blaschke T. 2009. Análise da Paisagem com SIG. Oficina de Textos. [[link]](https://www.ofitexto.com.br/livro/analise-da-paisagem-com-sig/)

Lepaine M, Usery EL. 2017. Choosing a Map Projection. Springer. [[link]](https://www.springer.com/gp/book/9783319518343)

Longley PA, Goodchild MF, Maguire DJ, Rhind DW. 2013. Sistemas e Ciência da Informação Geográfica. 3ed. Rio de Janeiro, Bookman. [[link]](https://loja.grupoa.com.br/sistemas-e-ciencia-da-informacao-geografica-ebook-p986339)

Minas Gerais – Secretaria de Estado de Meio Ambiente e Desenvolvimento Sustentável. 2019. Práticas de geoprocessamento em QGIS. 2 ed. Belo Horizonte: Semad. [[link]](http://www.meioambiente.mg.gov.br/images/stories/2019/GESTAO_AMBIENTAL/IDE/APOSTILA_QGIS_3.4_DGTA-SEMAD-190619.pdf)

QGIS Project. 2011. Documentação para QGIS 3.16. [[link]](https://docs.qgis.org/3.16/pt_BR/docs/index.html)

Paese A, Uezu A, Lorini ML, Cunha A. 2015. Conservação da biodiversidade com SIG. Oficina de Textos. [[link]](https://www.ofitexto.com.br/livro/conservacao-da-biodiversidade-com-sig-livro-digital/)

Souza RF, Falcão EC. 2017. Geoprocessamento aplicado: contexto multidisciplinar. Editora EFPB. [[link]](http://editora.ifpb.edu.br/index.php/ifpb/catalog/book/80)

Wegmann M, Leutner B, Dech S. 2016. Remote Sensing and GIS for Ecologists. Pelagic Publishing. [[link]](http://book.ecosens.org/rsebook/)

Wegmann M, Schwalb-Willmann J, Dech S. 2020. An Introduction to Spatial Data Analysis Remote Sensing and GIS with Open Source Software. Pelagic Publishing. [[link]](http://book.ecosens.org/gsbook/)

Xavier-da-Silva J. 2009. O que é Geoprocessamento? Revista do CREA-RJ, 79:42–44. [[link]](http://www.ufrrj.br/lga/tiagomarino/artigos/oqueegeoprocessamento.pdf)

Xavier-da-Silva J, Zaidan RT. 2004. Geoprocessamento & análise ambiental: aplicações. Bertrand Brasil.

Xavier-da-Silva J, Zaidan RT. 2011. Geoprocessamento & meio ambiente. Bertrand Brasil. [[link]](https://www.lojaofitexto.com.br/geoprocessamento-e-meio-ambiente/p)

Zanotta DC, Ferreira MP, Zortea M. 2019. Processamento de imagens de satélite. Oficina de Textos. [[link]](https://www.ofitexto.com.br/livro/processamento-de-imagens-de-satelite/)
